services:
  klotus-landing-page-api:
    build:
      context: /opt/repos/klotus-split/landing-page-api
      dockerfile: Dockerfile
    container_name: klotus-landing-page-api
    env_file:
      - /opt/repos/klotus-split/landing-page-api/.env
    restart: always
    networks:
      - npm-network

networks:
  npm-network:
    external: true
